# Generated by Django 3.1.7 on 2021-03-21 07:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0003_book'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='publisher_id',
            new_name='publisher',
        ),
    ]
